### ISSUE TITLE
fix double cards like Jerren, Corrupted Bishop // Ormendah

### ISSUE THREAD

**Issue by gfxblit** [gfxblit/mtgx#4]
CardPreview.tsx:23 Uncaught TypeError: Cannot read properties of undefined (reading 'png')
    at CardPreview (CardPreview.tsx:23:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at updateFunctionComponent (react-dom.development.js:20387:1)
    at beginWork (react-dom.development.js:22430:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)

**Comment by gfxblit** [comment]
(from hover over that card row)

**Comment by gfxblit** [comment]
https://github.com/gfxblit/mtgx/commit/851bf1dcbc926ab2d02380a8b5e9f758d7e486db
